[package]
name = "pty-process"
version = "0.1.0"
authors = ["Jesse Luehrs <doy@tozt.net>"]
edition = "2018"

[dependencies]
libc = "*"
nix = "0.17"
thiserror = "1.0"

async-io = { version = "1.3", optional = true }
async-process = { version = "1.0", optional = true }
tokio = { version = "1.2", optional = true, features = ["fs", "process", "net"] }
futures = { version = "0.3", optional = true }

[dev-dependencies]
smol = "*"

[features]
default = ["backend-std"]

backend-std = []
backend-async-std = ["async-io", "async-process"]
backend-smol = ["async-io", "async-process"]
backend-tokio = ["tokio", "futures"]
