[package]
name = "pty-process"
version = "0.2.0"
authors = ["Jesse Luehrs <doy@tozt.net>"]
edition = "2021"

description = "spawn commands attached to a pty"
repository = "https://git.tozt.net/pty-process"
readme = "README.md"
keywords = ["pty", "spawn", "execute", "process"]
categories = ["asynchronous", "command-line-interface"]
license = "MIT"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]

[dependencies]
libc = "0.2.112"
nix = "0.23.1"

async-io = { version = "1.6.0", optional = true }
async-process = { version = "1.3.0", optional = true }
futures-io = { version = "0.3.19", optional = true }

[dev-dependencies]
async-executor = "1.4.1"
async-std = { version = "1.10.0", features = ["unstable"] }
regex = "1.5.4"
smol = "1.2.5"
term_size = "0.3.2"
tokio = { version = "1.15.0", features = ["full"] }
tokio-util = { version = "0.6.9", features = ["compat"] }

[features]
default = []

async = ["async-io", "async-process", "futures-io"]

[patch.crates-io]
async-process = { git = "https://github.com/doy/async-process", branch = "status-drop" }
