[package]
name = "pty-process"
version = "0.1.0"
authors = ["Jesse Luehrs <doy@tozt.net>"]
edition = "2018"

[dependencies]
libc = "0.2"
nix = "0.20"
thiserror = "1.0"

async-io = { version = "1.3", optional = true }
async-process = { version = "1.0", optional = true }
tokio = { version = "1.2", optional = true, features = ["fs", "process", "net"] }
futures = { version = "0.3", optional = true }

[dev-dependencies]
async-std = { version = "1.9", features = ["unstable"] }
async-executor = "1.4"
smol = "1.2"
tokio = { version = "1.2", features = [ "rt-multi-thread", "macros", "io-std", "io-util" ] }

[features]
default = ["backend-std"]

backend-std = []
backend-async-std = ["async-io", "async-process"]
backend-smol = ["async-io", "async-process"]
backend-tokio = ["tokio", "futures"]
